# Generated by Django 2.2.1 on 2019-05-28 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('path', models.TextField(verbose_name='Path')),
                ('subject', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(verbose_name='Path')),
                ('session', models.CharField(max_length=255, verbose_name='Session')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservoir.Subject')),
            ],
            options={
                'verbose_name': 'Session',
            },
        ),
        migrations.CreateModel(
            name='BIDSFile',
            fields=[
                ('filename', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Filename')),
                ('sidecar', models.CharField(blank=True, max_length=255, null=True, verbose_name='JSON Sidecar')),
                ('path', models.TextField(verbose_name='Path')),
                ('task', models.CharField(blank=True, max_length=255, null=True, verbose_name='task')),
                ('acquisition', models.CharField(blank=True, max_length=255, null=True, verbose_name='acquisition')),
                ('ce', models.CharField(blank=True, max_length=255, null=True, verbose_name='ce')),
                ('reconstruction', models.CharField(blank=True, max_length=255, null=True, verbose_name='reconstruction')),
                ('dir', models.CharField(blank=True, max_length=255, null=True, verbose_name='dir')),
                ('run', models.CharField(blank=True, max_length=255, null=True, verbose_name='run')),
                ('proc', models.CharField(blank=True, max_length=255, null=True, verbose_name='proc')),
                ('modality', models.CharField(blank=True, max_length=255, null=True, verbose_name='modality')),
                ('echo', models.CharField(blank=True, max_length=255, null=True, verbose_name='echo')),
                ('recording', models.CharField(blank=True, max_length=255, null=True, verbose_name='recording')),
                ('suffix', models.CharField(blank=True, max_length=255, null=True, verbose_name='suffix')),
                ('scans', models.CharField(blank=True, max_length=255, null=True, verbose_name='scans')),
                ('fmap', models.CharField(blank=True, max_length=255, null=True, verbose_name='fmap')),
                ('datatype', models.CharField(blank=True, max_length=255, null=True, verbose_name='datatype')),
                ('extension', models.CharField(blank=True, max_length=255, null=True, verbose_name='extension')),
                ('magneticfieldstrength', models.IntegerField(blank=True, null=True, verbose_name='MagneticFieldStrength')),
                ('imagingfrequency', models.FloatField(blank=True, null=True, verbose_name='ImagingFrequency')),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manufacturer')),
                ('manufacturersmodelname', models.CharField(blank=True, max_length=255, null=True, verbose_name='ManufacturersModelName')),
                ('deviceserialnumber', models.CharField(blank=True, max_length=255, null=True, verbose_name='DeviceSerialNumber')),
                ('bodypartexamined', models.CharField(blank=True, max_length=255, null=True, verbose_name='BodyPartExamined')),
                ('patientposition', models.CharField(blank=True, max_length=255, null=True, verbose_name='PatientPosition')),
                ('softwareversions', models.CharField(blank=True, max_length=255, null=True, verbose_name='SoftwareVersions')),
                ('mracquisitiontype', models.CharField(blank=True, max_length=255, null=True, verbose_name='MRAcquisitionType')),
                ('seriesdescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='SeriesDescription')),
                ('protocolname', models.CharField(blank=True, max_length=255, null=True, verbose_name='ProtocolName')),
                ('scanningsequence', models.CharField(blank=True, max_length=255, null=True, verbose_name='ScanningSequence')),
                ('sequencevariant', models.CharField(blank=True, max_length=255, null=True, verbose_name='SequenceVariant')),
                ('scanoptions', models.CharField(blank=True, max_length=255, null=True, verbose_name='ScanOptions')),
                ('sequencename', models.CharField(blank=True, max_length=255, null=True, verbose_name='SequenceName')),
                ('imagetype', models.CharField(blank=True, max_length=255, null=True, verbose_name='ImageType')),
                ('seriesnumber', models.IntegerField(blank=True, null=True, verbose_name='SeriesNumber')),
                ('acquisitiontime', models.CharField(blank=True, max_length=255, null=True, verbose_name='AcquisitionTime')),
                ('acquisitionnumber', models.IntegerField(blank=True, null=True, verbose_name='AcquisitionNumber')),
                ('slicethickness', models.FloatField(blank=True, null=True, verbose_name='SliceThickness')),
                ('sar', models.FloatField(blank=True, null=True, verbose_name='SAR')),
                ('echotime', models.FloatField(blank=True, null=True, verbose_name='EchoTime')),
                ('repetitiontime', models.FloatField(blank=True, null=True, verbose_name='RepetitionTime')),
                ('inversiontime', models.FloatField(blank=True, null=True, verbose_name='InversionTime')),
                ('flipangle', models.IntegerField(blank=True, null=True, verbose_name='FlipAngle')),
                ('partialfourier', models.IntegerField(blank=True, null=True, verbose_name='PartialFourier')),
                ('baseresolution', models.IntegerField(blank=True, null=True, verbose_name='BaseResolution')),
                ('shimsetting', models.CharField(blank=True, max_length=255, null=True, verbose_name='ShimSetting')),
                ('txrefamp', models.FloatField(blank=True, null=True, verbose_name='TxRefAmp')),
                ('phaseresolution', models.IntegerField(blank=True, null=True, verbose_name='PhaseResolution')),
                ('receivecoilname', models.CharField(blank=True, max_length=255, null=True, verbose_name='ReceiveCoilName')),
                ('receivecoilactiveelements', models.CharField(blank=True, max_length=255, null=True, verbose_name='ReceiveCoilActiveElements')),
                ('pulsesequencedetails', models.CharField(blank=True, max_length=255, null=True, verbose_name='PulseSequenceDetails')),
                ('wipmemblock', models.CharField(blank=True, max_length=255, null=True, verbose_name='WipMemBlock')),
                ('reflinespe', models.IntegerField(blank=True, null=True, verbose_name='RefLinesPE')),
                ('consistencyinfo', models.CharField(blank=True, max_length=255, null=True, verbose_name='ConsistencyInfo')),
                ('percentphasefov', models.IntegerField(blank=True, null=True, verbose_name='PercentPhaseFOV')),
                ('phaseencodingsteps', models.IntegerField(blank=True, null=True, verbose_name='PhaseEncodingSteps')),
                ('acquisitionmatrixpe', models.IntegerField(blank=True, null=True, verbose_name='AcquisitionMatrixPE')),
                ('reconmatrixpe', models.IntegerField(blank=True, null=True, verbose_name='ReconMatrixPE')),
                ('pixelbandwidth', models.IntegerField(blank=True, null=True, verbose_name='PixelBandwidth')),
                ('dwelltime', models.FloatField(blank=True, null=True, verbose_name='DwellTime')),
                ('imageorientationpatientdicom', models.CharField(blank=True, max_length=255, null=True, verbose_name='ImageOrientationPatientDICOM')),
                ('inplanephaseencodingdirectiondicom', models.CharField(blank=True, max_length=255, null=True, verbose_name='InPlanePhaseEncodingDirectionDICOM')),
                ('conversionsoftware', models.CharField(blank=True, max_length=255, null=True, verbose_name='ConversionSoftware')),
                ('conversionsoftwareversion', models.CharField(blank=True, max_length=255, null=True, verbose_name='ConversionSoftwareVersion')),
                ('dcm2bidsversion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dcm2bidsVersion')),
                ('spacingbetweenslices', models.FloatField(blank=True, null=True, verbose_name='SpacingBetweenSlices')),
                ('vendorreportedechospacing', models.FloatField(blank=True, null=True, verbose_name='VendorReportedEchoSpacing')),
                ('echotrainlength', models.IntegerField(blank=True, null=True, verbose_name='EchoTrainLength')),
                ('bandwidthperpixelphaseencode', models.FloatField(blank=True, null=True, verbose_name='BandwidthPerPixelPhaseEncode')),
                ('effectiveechospacing', models.FloatField(blank=True, null=True, verbose_name='EffectiveEchoSpacing')),
                ('derivedvendorreportedechospacing', models.FloatField(blank=True, null=True, verbose_name='DerivedVendorReportedEchoSpacing')),
                ('totalreadouttime', models.FloatField(blank=True, null=True, verbose_name='TotalReadoutTime')),
                ('phaseencodingdirection', models.CharField(blank=True, max_length=255, null=True, verbose_name='PhaseEncodingDirection')),
                ('intendedfor', models.CharField(blank=True, max_length=255, null=True, verbose_name='IntendedFor')),
                ('multibandaccelerationfactor', models.IntegerField(blank=True, null=True, verbose_name='MultibandAccelerationFactor')),
                ('slicetiming', models.CharField(blank=True, max_length=255, null=True, verbose_name='SliceTiming')),
                ('phaseencodingaxis', models.CharField(blank=True, max_length=255, null=True, verbose_name='PhaseEncodingAxis')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservoir.Session')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservoir.Subject')),
            ],
            options={
                'verbose_name': 'BIDS File',
            },
        ),
    ]
